const fs = require('fs');
const path = require('path');

const configContent = `
// Generated by build script
(function () {
    const firebaseConfig = {
        apiKey: "${process.env.FIREBASE_API_KEY || ''}",
        authDomain: "${process.env.FIREBASE_AUTH_DOMAIN || ''}",
        projectId: "${process.env.FIREBASE_PROJECT_ID || ''}",
        storageBucket: "${process.env.FIREBASE_STORAGE_BUCKET || ''}",
        messagingSenderId: "${process.env.FIREBASE_MESSAGING_SENDER_ID || ''}",
        appId: "${process.env.FIREBASE_APP_ID || ''}"
    };

    const SUPABASE_URL = "${process.env.SUPABASE_URL || ''}";
    const SUPABASE_ANON_KEY = "${process.env.SUPABASE_ANON_KEY || ''}";

    function initializeServices() {
        try {
            if (typeof firebase === 'undefined') {
                setTimeout(initializeServices, 100);
                return;
            }
            if (typeof window.supabase === 'undefined') {
                setTimeout(initializeServices, 100);
                return;
            }

            firebase.initializeApp(firebaseConfig);
            const auth = firebase.auth();
            const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

            window.auth = auth;
            window.supabase = supabase;

            console.log('✅ Services initialized from Environment Variables');
        } catch (error) {
            console.error('Error initializing services:', error);
        }
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', initializeServices);
    } else {
        initializeServices();
    }
})();
`;

fs.writeFileSync(path.join(__dirname, '../config.js'), configContent);
console.log('✅ config.js has been generated successfully.');
